package com.stemcell.swing.components;

import com.stemcell.common.beans.CredentialsBean;
import com.stemcell.common.i18n.I18nManager;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;

/**
 * Tela de Sobre...
 */
public class AboutBox extends javax.swing.JDialog {
    
    public static String getDadosTextuais(CredentialsBean credentialsBean) {
        StringBuilder sb = new StringBuilder();
        try {
            InputStream is = AboutBox.class.getResourceAsStream("/buildinfo");
            BufferedReader reader = new BufferedReader(new InputStreamReader(is));
            
            while (reader.ready()) {
                sb.append(reader.readLine()).append("\r\n");
            }
            reader.close();
            is.close();
        } catch (Exception e) {
            sb.append("\r\n\r\n").append(I18nManager.getString("swing.components.noBuildData"));
        }
        if (credentialsBean!=null) {
            sb.append("\r\n");
            sb.append(credentialsBean.getUsername());
            sb.append("\r\n\r\n--------------------------------------\r\n\r\n");
            for (String string : credentialsBean.getSecurityResources()) {
                sb.append(string).append("\r\n");
            }

        }
        sb.append("\r\n\r\nSystem Properties:\r\n");
        for (Object object : System.getProperties().keySet()) {
            if (object!=null) {
                sb.append(object).append(": ").append(System.getProperty(object.toString())).append( "\r\n");
            }
        }   
        return sb.toString();
    }
    /**
     * Cria o dialog.
     * @param parent Frame pai.
     * @param modal true, se for modal.
     */
    public AboutBox(java.awt.Frame parent, boolean modal, CredentialsBean credentialsBean, String dados, String titulo, String subTitulo) {
        super(parent, modal);
        initComponents();
        labelsubTitulo.setText(subTitulo);
        labelTitulo1.setText(titulo);
        StringBuilder sb = new StringBuilder();
        sb.append(dados);
        sb.append("\r\n\r\n");
        sb.append( getDadosTextuais(credentialsBean) );
        textDados.setText(sb.toString());
        textDados.setCaretPosition(0);
        setLocationRelativeTo(null);
//        TODO: Adicionar imagem
//        Image img = BaseApp.getApplication().getSplashScreenImage();
//        if (img!=null) {
//            imagem.setIcon(new ImageIcon(img));
//            imagem.setText("");
//        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        labelTitulo1 = new javax.swing.JLabel();
        labelsubTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDados = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);
        setUndecorated(true);

        layeredPane.setMinimumSize(new java.awt.Dimension(420, 300));
        layeredPane.setName("layeredPane"); // NOI18N

        labelTitulo1.setFont(labelTitulo1.getFont().deriveFont(labelTitulo1.getFont().getStyle() | java.awt.Font.BOLD, labelTitulo1.getFont().getSize()+7));
        labelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitulo1.setText("---");
        labelTitulo1.setName("labelTitulo1"); // NOI18N
        labelTitulo1.setBounds(10, 10, 380, -1);
        layeredPane.add(labelTitulo1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelsubTitulo.setFont(labelsubTitulo.getFont().deriveFont(labelsubTitulo.getFont().getStyle() | java.awt.Font.BOLD, labelsubTitulo.getFont().getSize()+7));
        labelsubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelsubTitulo.setText("---");
        labelsubTitulo.setName("labelsubTitulo"); // NOI18N
        labelsubTitulo.setBounds(10, 30, 380, 20);
        layeredPane.add(labelsubTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        textDados.setColumns(20);
        textDados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textDados.setRows(5);
        textDados.setName("textDados"); // NOI18N
        textDados.setOpaque(false);
        textDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clique(evt);
            }
        });
        jScrollPane1.setViewportView(textDados);

        jScrollPane1.setBounds(10, 70, 380, 150);
        layeredPane.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("swing-components-messages"); // NOI18N
        jButton1.setText(bundle.getString("fcorp.swing.components.close")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar(evt);
            }
        });
        jButton1.setBounds(20, 250, 70, 30);
        layeredPane.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imagem.setName("imagem"); // NOI18N
        imagem.setBounds(0, 0, 400, 300);
        layeredPane.add(imagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de clique. Fecha o dialog.
     * @param evt O evento do mouse.
     */
    private void clique(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clique
        
    }//GEN-LAST:event_clique

private void fechar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar
    dispose();
}//GEN-LAST:event_fechar
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelsubTitulo;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JTextArea textDados;
    // End of variables declaration//GEN-END:variables
    
}
