package com.stemcell.swing.components;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileWriter;
import javax.swing.AbstractAction;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 * Diálogo para exibir mensagem de erro não tratado
 */
public class UnknownExceptionDialog extends FinalizeOnDisposeDialog {
    private static int visibleDialogsCount=0;
    public static final Icon errorIcon;
    public String errorText;
    
    static {
        try {
            errorIcon = (Icon) UIManager.get("OptionPane.errorIcon");
        } finally {}
    }
    
    /** Creates new form UnknownExceptionDialog */
    public UnknownExceptionDialog(java.awt.Frame parent, String text) {
        super(parent, true);
        this.errorText = text;
        initComponents();
        jLabel2.setIcon(errorIcon);
        jButton1.setAction(new AbstractAction("Fechar") {
            public void actionPerformed(ActionEvent arg0) {
                dispose();
            }
        });
        setLocationRelativeTo(null);
        pack();
    }

    @Override
    public void setVisible(boolean visible) {
        visibleDialogsCount++;
        super.setVisible(visible);
        visibleDialogsCount--;
    }

    public static int getVisibleDialogsCount() {
        return visibleDialogsCount;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btGravarReport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btVerReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("swing-components-messages"); // NOI18N
        setTitle(bundle.getString("fcorp.swing.components.errorTitle")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(bundle.getString("fcorp.swing.components.errorMessage")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText(bundle.getString("fcorp.swing.components.close")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });

        btGravarReport.setText(bundle.getString("fcorp.swing.components.errorWriteReport")); // NOI18N
        btGravarReport.setName("btGravarReport"); // NOI18N
        btGravarReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarReportActionPerformed(evt);
            }
        });

        jLabel2.setText("     ");
        jLabel2.setName("jLabel2"); // NOI18N

        btVerReport.setText(bundle.getString("fcorp.swing.components.errorShowReport")); // NOI18N
        btVerReport.setName("btVerReport"); // NOI18N
        btVerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerReportActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 486, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btVerReport)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btGravarReport)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(btGravarReport)
                    .add(btVerReport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close
       dispose();
    }//GEN-LAST:event_close

private void btGravarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarReportActionPerformed
    JFileChooser jfc = new JFileChooser();
    jfc.setDialogTitle("Gravar relatório de erros");
    jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jfc.setMultiSelectionEnabled(false);
    if (jfc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION) {
        File f = jfc.getSelectedFile();
        if (!f.getName().toLowerCase().endsWith(".txt")) {
            f = new File( String.format("%s.txt", f.getPath()) );
        }
        saveReport(f);
    }
    dispose();
}//GEN-LAST:event_btGravarReportActionPerformed

private void btVerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerReportActionPerformed
    try {
        File f = File.createTempFile("erro_", ".txt");
        f.deleteOnExit();
        saveReport(f);
        Desktop.getDesktop().open(f);
    } catch (Exception e) {  // SUPPRESS CHECKSTYLE Illegal Catch - Barreira de excecao
        DialogMessages.error(this, e.getMessage());
    }
}//GEN-LAST:event_btVerReportActionPerformed
    
private void saveReport(File selectedFile) {
    FileWriter fout = null;
    try {
        fout = new FileWriter(selectedFile);
        fout.write(errorText);
        fout.close();
    } catch (Exception e) {  // SUPPRESS CHECKSTYLE Illegal Catch - Barreira de excecao
        DialogMessages.error(this, e.getMessage());
    } finally {
        try {
            fout.close();
        } catch (Exception e){ // SUPPRESS CHECKSTYLE Illegal Catch - Barreira de excecao
            return;
        }
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btGravarReport;
    javax.swing.JButton btVerReport;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
